version: "{build}"

branches:
  only:
    - master

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

before_build:
  - git submodule update --init --recursive
  - nuget restore IIS.Compression\Compression.sln

build_script:
  - msbuild IIS.Compression\iiszlib\iiszlib.vcxproj /p:platform=x86 /p:configuration=Release /v:m
  - msbuild IIS.Compression\iiszlib\iiszlib.vcxproj /p:platform=x64 /p:configuration=Release /v:m
  - msbuild IIS.Compression\iisbrotli\iisbrotli.vcxproj /p:platform=x86 /p:configuration=Release /v:m
  - msbuild IIS.Compression\iisbrotli\iisbrotli.vcxproj /p:platform=x64 /p:configuration=Release /v:m

test: off

after_build:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq $true) {
          xcopy .\IIS.Compression\bin\Release\x86\* .\build\32bit\ /I
          xcopy .\IIS.Compression\bin\Release\x64\* .\build\64bit\ /I
          nuget pack .\IIS.Compression.SiteExtension.nuspec -BasePath .\build -OutputDirectory .\ -Version $($env:APPVEYOR_REPO_TAG_NAME.Substring(1))
      }

artifacts:
  - path: '*.nupkg'

deploy:
  - provider: NuGet
    api_key: $(NUGET_API_KEY)
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true