trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- checkout: self
  submodules: recursive

- task: NuGetCommand@2
  displayName: 'nuget restore'
  inputs:
    command: 'restore'
    restoreSolution: 'IIS.Compression\Compression.sln'

- task: MSBuild@1
  displayName: 'Build x86'
  inputs:
    solution: 'IIS.Compression\Compression.sln'
    platform: 'x86'
    configuration: 'Release'
    msbuildArguments: '/v:m'

- task: MSBuild@1
  displayName: 'Build x64'
  inputs:
    solution: 'IIS.Compression\Compression.sln'
    platform: 'x64'
    configuration: 'Release'
    msbuildArguments: '/v:m'

- script: |
    xcopy .\IIS.Compression\bin\Release\x86\* .\build\32bit\ /I
    xcopy .\IIS.Compression\bin\Release\x64\* .\build\64bit\ /I
    nuget pack .\IIS.Compression.SiteExtension.nuspec -BasePath .\build -OutputDirectory .\
  displayName: 'pack nuget'