trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- checkout: self
  submodules: true

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'

- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    platform: 'x86'
    configuration: 'Release'
    msbuildArguments: '/v:m'

- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    platform: 'x64'
    configuration: 'Release'
    msbuildArguments: '/v:m'